# Generated by Django 3.2.15 on 2022-10-28 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuxHookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtm_created', models.DateTimeField(auto_now_add=True, verbose_name='DTM Created')),
                ('dtm_updated', models.DateTimeField(auto_now=True, verbose_name='DTM Updated')),
                ('slug', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=16)),
                ('description', models.CharField(blank=True, default=None, max_length=64, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuxHook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtm_created', models.DateTimeField(auto_now_add=True, verbose_name='DTM Created')),
                ('dtm_updated', models.DateTimeField(auto_now=True, verbose_name='DTM Updated')),
                ('slug', models.CharField(max_length=8, unique=True)),
                ('user', models.CharField(max_length=32)),
                ('app', models.CharField(max_length=32)),
                ('task', models.CharField(max_length=64)),
                ('url', models.URLField()),
                ('secret', models.CharField(blank=True, default=None, max_length=16, null=True)),
                ('is_validated', models.DateTimeField(blank=True, default=None, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quxhook.quxhookevent')),
            ],
            options={
                'verbose_name': 'QuxHook',
                'verbose_name_plural': 'QuxHooks',
                'db_table': 'quxhook',
                'unique_together': {('user', 'app', 'task', 'event')},
            },
        ),
    ]
